# Generated by Django 6.0.4 on 2026-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='0', max_length=255)),
                ('status', models.CharField(choices=[('SAFE', 'SAFE'), ('SMOKE DETECTED', 'SMOKE DETECTED'), ('FIRE ALERT', 'FIRE ALERT')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
